apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-idp-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: enterprise-idp
  source:
    repoURL: https://github.com/niloykumarbarman/-Internal-Developer-Platform-IDP-.git
    targetRevision: main
    path: infrastructure/argocd
    directory:
      recurse: false
      include: '*.yaml'
      exclude: 'app-of-apps.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
