apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-idp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: enterprise-idp
  source:
    repoURL: https://github.com/niloykumarbarman/-Internal-Developer-Platform-IDP-.git
    targetRevision: main
    path: helm/enterprise-idp
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: enterprise-idp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
