apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  db-connection: {{ .Values.backend.secrets.dbConnection | b64enc | quote }}
  jwt-secret: {{ .Values.backend.secrets.jwtSecret | b64enc | quote }}
  github-token: {{ .Values.backend.secrets.githubToken | b64enc | quote }}
  postgresql-password: {{ .Values.secrets.postgresqlPassword | b64enc | quote }}
  redis-password: {{ .Values.secrets.redisPassword | b64enc | quote }}
